apiVersion: v1
kind: Service
metadata:
  name: mosquitto-mqtt
  annotations:
    metallb.universe.tf/address-pool: mosquitto-mqtt
  labels:
    {{- include "helm.selectorLabels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mqtt
    - protocol: TCP
      port: 9001
      targetPort: 9001
      name: mqtt-websocket
